// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpsyqxobhtglkpejybjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwc3lxeG9iaHRnbGtwZWp5YmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mzc4ODIsImV4cCI6MjA2NDUxMzg4Mn0.N0Su6CyxaaWgR4VLKcsrCWsvofgtVPkEkXWG7FOGyk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);